/** Shared schematic / logic symbol ids for quiz banks + SVG renderer. */
export type SchematicSymbolId =
  | 'resistor'
  | 'capacitor'
  | 'diode'
  | 'led'
  | 'inductor'
  | 'battery'
  | 'ground'
  | 'lamp'
  | 'npn'
  | 'pnp'
  | 'switch'
  | 'fuse'
  | 'transformer'
  | 'ac'
  | 'potentiometer'
  | 'motor'
  | 'zener'
  | 'and'
  | 'or'
  | 'not'
  | 'nand'
  | 'nor'
  | 'xor'
