'use client'

import type { LucideIcon } from 'lucide-react'
import {
  Award,
  BarChart3,
  BookOpen,
  ClipboardList,
  FolderTree,
  Globe,
  GraduationCap,
  Gamepad2,
  HardHat,
  Headphones,
  LayoutDashboard,
  Mail,
  Megaphone,
  Monitor,
  Receipt,
  Settings,
  Shield,
  Star,
  ShoppingBag,
  Package,
  UserCog,
  Users,
  Video,
  Warehouse,
  Zap,
} from 'lucide-react'
import type { AdminNavIconName } from '@/lib/admin/nav'

export const ADMIN_NAV_ICONS: Record<AdminNavIconName, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  users: Users,
  'graduation-cap': GraduationCap,
  'user-cog': UserCog,
  'hard-hat': HardHat,
  shield: Shield,
  'clipboard-list': ClipboardList,
  receipt: Receipt,
  award: Award,
  'shopping-bag': ShoppingBag,
  package: Package,
  warehouse: Warehouse,
  'folder-tree': FolderTree,
  'book-open': BookOpen,
  video: Video,
  monitor: Monitor,
  megaphone: Megaphone,
  globe: Globe,
  gamepad: Gamepad2,
  zap: Zap,
  headphones: Headphones,
  'bar-chart': BarChart3,
  settings: Settings,
  mail: Mail,
  star: Star,
}
